### ISSUE TITLE
zastąpić domyślny błąd na nasz gdy nie ma caregiver id lub student id

### ISSUE THREAD

**Issue by pyexplorerhs3** [zetonteam/zeton_django#95] opened 2024-05-22 18:59 UTC
Invalid pk - object does not exist.  <- to trzeba poprawić.

@bartmkraus ?? wyjasnisz

**Comment by bartmkraus** [comment] 2024-05-23 06:13
As far as I remember, this was related to the default error message, which doesn't give us as much information as would be required to track down the cause and would have been better changed to a more descriptive one. I added this a long time ago and I guess it wasn't that important. @MateuszBelczowski , maybe you remember something more than me? 😅

**Comment by arkjedrz** [comment] 2024-09-29 14:51
It's either not relevant anymore, or will get fixed with #172

**Closed as not planned by arkjedrz** 2024-09-29 14:51 UTC
